# 🐻‍❄️❄ Snowflake: Easy to use Kotlin library to help you generate Twitter snowflakes asynchronously
# Copyright (c) 2022-2023 Noelware Team <team@noelware.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Release snapshot version
on:
  release:
    types:
      - prereleased
jobs:
  release:
    name: Snapshot release (${{matrix.release.prettyName}}
    runs-on: ${{matrix.release.runner}}
    strategy:
      matrix:
        release:
          - { prettyName: "JS/JVM/Native - Linux x86_64", runner: ubuntu-latest,  publishTask: publish                                   }
          - { prettyName: "Native - Windows",             runner: windows-latest, publishTask: publishNativePublicationToMavenRepository }
          - { prettyName: "Native - macOS",               runner: macos-latest,   publishTask: publishNativePublicationToMavenRepository }
          - { prettyName: "Native - Linux ARM",           runner: self-hosted,    publishTask: publishNativePublicationToMavenRepository }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          architecture: ${{matrix.release.runner == 'self-hosted' && 'aarch64' || 'amd64'}}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lint code-base with Spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck --no-daemon --scan

      - name: Compiles Kotlin source sets
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :snowflake:compileKotlin --no-daemon --scan

      - name: Release!
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{matrix.runner.publishTask}} -Dorg.gradle.s3.endpoint=${{secrets.S3_ENDPOINT}}
        env:
          NOELWARE_PUBLISHING_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          NOELWARE_PUBLISHING_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          NOELWARE_PUBLISHING_IS_SNAPSHOT: "true"
